name: Actions Workflow
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  Run-Github-Actions:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update pip
        run: pip install -U pip setuptools wheel
      - name: Flake8
        run: |
            pip3 install flake8
            flake8 . --count --max-line-length=120 --show-source --statistics
      - name: Mypy
        run: |
          pip install -U mypy
          for f in $(find ./ -name "*.py"); do
            mypy --python-version 3.8 --show-error-context --platform 'linux' "$f"
          done
      - name: Pytest
        run: |
          pip install -U pytest
          pytest .
  deps-vulnerable-check:
    name: 'Vulnerable Dependency Check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: actions/checkout@v3
      - run: |
          pip install -U pip setuptools wheel
          pip install pyinstaller pip-audit 
          pip-audit -r requirements.txt
