name: Actions Workflow
on:
  push:

jobs:
  Run-Github-Actions:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update pip
        run: pip install -U pip setuptools wheel
      - name: Flake8
        run: |
            pip3 install flake8
            flake8 . --count --max-line-length=120 --show-source --statistics
      - name: Mypy
        run: |
          pip install -U mypy
          for f in $(find ./ -name "*.py"); do
            mypy --python-version 3.8 --show-error-context --platform 'linux' "$f"
          done
          # mypy --config-file mypy.ini --exclude 03-LogisticRegression/main.py .
      - name: Pytest
        run: |
          pip install -U pytest
          pytest .
