name: Actions Workflow
on:
  push:

jobs:
  run-github-actions:
    name: Run Github Actions
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Flake8 
        run: flake8 . --count --max-line-length=120 --show-source --statistics 
